### ISSUE TITLE
Erros em log

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-frenet#4]
Este app segue dando alguns erros, pode dar uma olhada @talissonf ?

```console
ecomplus-integrations [Mon Nov 11 2019 14:28:46 GMT-0200 (Brasilia Summer Time)] 
FRENET_REQUEST_ERROR
Error: Frenet api request failed.
    at Request.rq.post [as _callback] (/var/nodejs/frenet/src/calculate.js:130:20)
    at Request.self.callback (/var/nodejs/frenet/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/var/nodejs/frenet/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/var/nodejs/frenet/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  ---  //  ---  

ecomplus-integrations [Mon Nov 11 2019 15:58:45 GMT-0200 (Brasilia Summer Time)] 
FRENET_REQUEST_ERROR
Error: Frenet api request failed.
    at Request.rq.post [as _callback] (/var/nodejs/frenet/src/calculate.js:130:20)
    at Request.self.callback (/var/nodejs/frenet/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/var/nodejs/frenet/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/var/nodejs/frenet/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  ---  //  ---  

ecomplus-integrations [Wed Nov 13 2019 22:23:23 GMT-0200 (Brasilia Summer Time)] 
FRENET_REQUEST_ERROR
TypeError: Cannot read property 'filter' of undefined
    at toEcomplusSchema (/var/nodejs/frenet/src/calculate.js:76:58)
    at apiRequest.then.result (/var/nodejs/frenet/src/calculate.js:155:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  ---  //  --- 
```

**Comment by talissonf** [comment]
Vou verificar.
